spring:
  application:
    name: jup-jup
  server:
    port: 8084

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jupjup?serverTimezone=Asia/Seoul
    username: root
    password: jupjup1234


  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 541126883288-3qnon1d9hnllfaho31opp2kbaleaifg1.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://jupjup.store/login/oauth2/code/google
    #        redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email

          naver:
            client-name: naver
            client-id: P5rU2N4nihmGgZW9cU08
            client-secret: EP1mnn2SSo
            redirect-uri: https://jupjup.store/login/oauth2/code/naver
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
          kakao:
            client-id: 86cf25712d4c66f5fbd8dc40b7eae343
            #            client-secret: xYbgONC3rGbArKh5nM20YIPXI0pv4eyj // 오류로 인한 주석 ( 이거 켜놓으니깐 로긴이 안됨 ;; 왜지 )
            scope: profile_nickname
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: https://jupjup.store/login/oauth2/code/kakao
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: your_jwt_secret_here@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  refresh-secret: your_jwt_refresh_secret_here@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

springdoc:
  swagger-ui:
    url: '/docs/api.yaml'

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true
